<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_PostalCode</name>
   <tag></tag>
   <elementGuidId>c55b660a-6de5-4f1b-bab3-8a172896b9fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div/div[2]/div[1]/div[4]/table/tbody/tr[6]/td[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div/div[2]/div[1]/div[4]/table/tbody/tr[6]/td[2]/input</value>
   </webElementProperties>
</WebElementEntity>
