<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Amount</name>
   <tag></tag>
   <elementGuidId>02bf8aee-da40-43af-b46c-fd5ed88375f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div/div[2]/div[1]/div[2]/table/tbody/tr[1]/td[3]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div/div[2]/div[1]/div[2]/table/tbody/tr[1]/td[3]/input</value>
   </webElementProperties>
</WebElementEntity>
